import { useState } from 'react';
import { motion } from 'framer-motion';
import { FileCheck2, Download, FileText, Hash, ShieldCheck, Loader2, Gavel } from 'lucide-react';
import { GlassCard, SectionHeading, StatusDot } from '../components/GlassCard';
import { PageHeader } from '../components/PageTransition';
import { evidenceTimeline } from '../data/mock';
import jsPDF from 'jspdf';

const tagColor: Record<string, string> = {
  call: 'text-cyan-300',
  ai: 'text-violet-300',
  transaction: 'text-rose-300',
  action: 'text-amber-300',
  evidence: 'text-emerald-300',
};

export function EvidencePage() {
  const [generating, setGenerating] = useState(false);
  const complaintId = 'RAK-4821-CFC';

  const downloadPDF = () => {
    setGenerating(true);
    setTimeout(() => {
      const doc = new jsPDF();
      const w = doc.internal.pageSize.getWidth();

      // Header band
      doc.setFillColor(10, 14, 26);
      doc.rect(0, 0, w, 28, 'F');
      doc.setTextColor(34, 211, 238);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('RAKSHAK AI — COURT-READY EVIDENCE REPORT', w / 2, 13, { align: 'center' });
      doc.setTextColor(180, 180, 180);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.text('Digital Public Safety Intelligence Platform', w / 2, 20, { align: 'center' });
      doc.text(`Complaint ID: ${complaintId}  |  Generated: ${new Date().toLocaleString()}`, w / 2, 25, { align: 'center' });

      let y = 40;
      doc.setTextColor(20, 20, 20);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text('1. Case Summary', 14, y);
      y += 7;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      const summary = [
        'Subject was targeted by a digital-arrest scam call impersonating a TRAI official.',
        'Caller threatened imminent arrest and demanded fund transfer for "verification".',
        'AI detection engine flagged the call with risk score 87/100 (confidence 94%).',
        'Attempted transfer of Rs. 4,20,000 to UPI ID fraudster@upi via HDFC account ..4821.',
        'Bank freeze requested via 1930 helpline; evidence package sealed with hash 0x8af2...c19d.',
      ];
      summary.forEach((s) => {
        const lines = doc.splitTextToSize(`- ${s}`, w - 28);
        doc.text(lines, 14, y);
        y += lines.length * 5 + 1;
      });

      y += 4;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('2. Evidence Timeline', 14, y);
      y += 7;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      evidenceTimeline.forEach((e) => {
        doc.setTextColor(34, 211, 238);
        doc.setFont('helvetica', 'bold');
        doc.text(e.time, 14, y);
        doc.setTextColor(20, 20, 20);
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(`${e.title} — ${e.detail}`, w - 50);
        doc.text(lines, 32, y);
        y += lines.length * 5 + 2;
      });

      y += 4;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('3. Chain of Custody', 14, y);
      y += 7;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      const custody = [
        '14:05 — Evidence sealed by Rakshak AI (hash 0x8af2...c19d)',
        '14:12 — Transferred to Cyber Crime Cell, Delhi',
        '14:30 — Acknowledged by Insp. R. Verma (badge D-4412)',
        'Integrity verified — no modification detected.',
      ];
      custody.forEach((c) => {
        doc.text(`- ${c}`, 14, y);
        y += 5;
      });

      y += 6;
      doc.setDrawColor(200, 200, 200);
      doc.line(14, y, w - 14, y);
      y += 6;
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text('This document was generated by Rakshak AI and is admissible as digital evidence under IT Act Section 65B.', 14, y);
      doc.text('Prototype demonstration — all data is synthetic.', 14, y + 5);

      doc.save(`Rakshak_Evidence_${complaintId}.pdf`);
      setGenerating(false);
    }, 1400);
  };

  return (
    <div>
      <PageHeader
        title="Evidence Generator"
        subtitle="AI-generated investigation report with a court-ready evidence layout, timeline cards and a downloadable PDF for legal proceedings."
        icon={<FileCheck2 className="h-6 w-6 text-cyan-300" />}
      />

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Timeline */}
        <GlassCard className="p-6 lg:col-span-2">
          <SectionHeading label="Forensics" title="Evidence Timeline" />
          <div className="relative">
            <div className="absolute left-3 top-0 h-full w-px bg-gradient-to-b from-cyan-400/40 via-violet-400/30 to-transparent" />
            <div className="space-y-4">
              {evidenceTimeline.map((e, i) => (
                <motion.div key={i} initial={{ opacity: 0, x: -12 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.1 }} className="relative flex gap-4">
                  <div className="z-10 mt-1 grid h-7 w-7 shrink-0 place-items-center rounded-full bg-ink-850 ring-2 ring-cyan-400/40">
                    <StatusDot status={e.tag === 'transaction' ? 'fail' : e.tag === 'action' ? 'warn' : 'info'} />
                  </div>
                  <div className="flex-1 rounded-xl border border-white/10 bg-white/[0.03] p-4">
                    <div className="flex items-center justify-between">
                      <p className="text-sm font-semibold text-slate-100">{e.title}</p>
                      <span className={`font-mono text-xs ${tagColor[e.tag]}`}>{e.time}</span>
                    </div>
                    <p className="mt-1.5 text-xs text-slate-400">{e.detail}</p>
                    <span className={`chip mt-2 text-[10px] ${tagColor[e.tag]}`}>{e.tag}</span>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </GlassCard>

        {/* Report panel */}
        <div className="space-y-6">
          <GlassCard className="p-6">
            <SectionHeading label="Report" title="Investigation Report" />
            <div className="space-y-3 text-sm">
              <div className="flex items-center justify-between rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2">
                <span className="flex items-center gap-2 text-slate-400"><Hash className="h-3.5 w-3.5" /> Complaint ID</span>
                <span className="font-mono text-cyan-300">{complaintId}</span>
              </div>
              <div className="flex items-center justify-between rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2">
                <span className="flex items-center gap-2 text-slate-400"><ShieldCheck className="h-3.5 w-3.5" /> Evidence Hash</span>
                <span className="font-mono text-xs text-slate-300">0x8af2...c19d</span>
              </div>
              <div className="flex items-center justify-between rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2">
                <span className="flex items-center gap-2 text-slate-400"><Gavel className="h-3.5 w-3.5" /> Admissibility</span>
                <span className="chip text-emerald-300">IT Act §65B</span>
              </div>
            </div>
          </GlassCard>

          <GlassCard className="p-6">
            <div className="flex items-center gap-2 text-sm font-semibold text-cyan-300">
              <FileText className="h-4 w-4" /> AI-Generated Summary
            </div>
            <p className="mt-3 text-xs leading-relaxed text-slate-400">
              The subject received a digital-arrest scam call at 14:02. AI flagged the call at 14:02:53 with risk
              score 87. A fund transfer of ₹4,20,000 was attempted to fraudster@upi. Bank freeze was requested
              via 1930 at 14:04:10. Evidence sealed with cryptographic hash and chain-of-custody initiated.
            </p>
            <button onClick={downloadPDF} disabled={generating} className="btn-primary mt-4 w-full">
              {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
              {generating ? 'Generating PDF…' : 'Download PDF Report'}
            </button>
          </GlassCard>
        </div>
      </div>
    </div>
  );
}
